Catch if branches are the same.

diff --git a/src/commands/merge-with-parent.yml b/src/commands/merge-with-parent.yml
--- a/src/commands/merge-with-parent.yml
+++ b/src/commands/merge-with-parent.yml
@@ -10,6 +10,7 @@ parameters:
       always be merged in to. The parent branch will attempt to be discovered
       if this is blank.
     default: ""
+  
 
 steps:
   - when:
@@ -19,6 +20,10 @@ steps:
             name: Merge current branch with <<parameters.parent>>
             command: |
               CHILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+              if [ "$CHILD_BRANCH" -eq "<<parameters.parent>>" ]; then
+                echo "Can't merge branch into itself!"
+                exit 1
+              fi
               git checkout <<parameters.parent>>
               git merge $CHILD_BRANCH
   - when:
@@ -26,9 +31,13 @@ steps:
         not: <<parameters.parent>>
       steps:
         - run:
-            name: Merge current branch detected parent
+            name: Merge current branch with parent
             command: |
               CHILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
               PARENT_BRANCH=$(git show-branch | sed "s/].*//" | grep "\*" | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed "s/^.*\[//")
+              if [ "$CHILD_BRANCH" -eq "$PARENT_BRANCH" ]; then
+                echo "Can't merge branch into itself!"
+                exit 1
+              fi
               git checkout $PARENT_BRANCH
               git merge $CHILD_BRANCH
